apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: docker12388/project-frontend:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: frontend-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: default
  labels:
    app: frontend
    environment: production
data:
  REACT_APP_API_URL: "http://backend-service.default.svc.cluster.local:5000"
  REACT_APP_ENV: "production"