import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger, } from "@/components/ui/dropdown-menu";
import { cn } from "@/lib/utils";
import { Calendar, Link, Phone, Users, Video } from "lucide-react";
const CallMenu = ({ name, disabled, onVoiceCall, onVideoCall }) => {
    return (_jsxs(DropdownMenu, { children: [_jsx(DropdownMenuTrigger, { asChild: true, children: _jsx(Button, { size: "icon", variant: "ghost", className: "rounded-full", "aria-label": "Call options", children: _jsx(Phone, { className: "size-4" }) }) }), _jsxs(DropdownMenuContent, { className: "w-72 p-3", align: "end", sideOffset: 8, children: [_jsxs("div", { className: "flex items-center gap-2 px-1 pb-3", children: [_jsx("div", { className: "size-8 rounded-full bg-muted flex items-center justify-center text-xs", children: name?.slice(0, 1).toUpperCase() }), _jsx("div", { className: "text-sm font-medium", children: name })] }), _jsxs("div", { className: "flex gap-2", children: [_jsxs(Button, { className: cn("flex-1 bg-emerald-500 text-white hover:bg-emerald-600", disabled && "opacity-60"), onClick: onVoiceCall, disabled: disabled, children: [_jsx(Phone, { className: "size-4" }), "Voice"] }), _jsxs(Button, { className: cn("flex-1 bg-emerald-500 text-white hover:bg-emerald-600", disabled && "opacity-60"), onClick: onVideoCall, disabled: disabled, children: [_jsx(Video, { className: "size-4" }), "Video"] })] }), _jsx(DropdownMenuSeparator, { className: "my-3" }), _jsxs(DropdownMenuItem, { disabled: true, children: [_jsx(Users, { className: "size-4" }), "New group call"] }), _jsxs(DropdownMenuItem, { disabled: true, children: [_jsx(Link, { className: "size-4" }), "Send call link"] }), _jsxs(DropdownMenuItem, { disabled: true, children: [_jsx(Calendar, { className: "size-4" }), "Schedule call"] })] })] }));
};
export default CallMenu;
